### ISSUE TITLE
ionic 2 sample

### ISSUE THREAD

**Issue by coolman7** [tomloprod/cordova-plugin-appminimize#2]
Hello,
Thank you for this plugin. Is it possible to share how can we use this plugin with ionic 2?
Thanks

**Comment by tomloprod** [comment]
Hi @coolman7.  I have no tried this, but I guess this should work:

Add this after the imports:

    declare var cordova:any;

And use the plugin as follow:

    platform.ready().then(
        () => {
            console.log("MyApp::constructor platform.ready");
            window.plugins.appMinimize.minimize();
        }
    );

Try and tell me if works :-)

Regards,

**Comment by tomloprod** [comment]
And, please, if this plugin is useful for you, give it a star ;-)

**Comment by coolman7** [comment]
This code does not what I need. I need when use press back button at home screen, app will not exit, just minimize. Maybe I need ionic 2 equivalent of this:
```
$ionicPlatform.registerBackButtonAction(function (event) {
    event.preventDefault();
    window.plugins.appMinimize.minimize();
}, 100);
```
Thanks

**Comment by tomloprod** [comment]
See my updated answer. The last code should work.

**Comment by coolman7** [comment]
This code is working. Thank you for help.
```
this.platform.registerBackButtonAction(() => {
         window['plugins'].appMinimize.minimize();
});
```

**Comment by tomloprod** [comment]
Amazing, thank you for share your solution.

**Comment by coolman7** [comment]
I don't understand why 
`window.plugins` does not work but `window.['plugins']` works. Do you have any idea?

**Comment by tomloprod** [comment]
No, really. `window.plugins` should work. Do you see any error when use this?

**Comment by coolman7** [comment]
Typescript error: `Property 'plugins' does not exist on type 'Window'`

**Comment by tomloprod** [comment]
As I see, the array property works because Typescript doesn't check if is defined on initial build —Unlike the `plugins` property— so it safely passes inspection... 

Take a look to this SO answer: [Using TypeScript with PhoneGap/Cordova Plugins](http://stackoverflow.com/a/17708034/4359029)

**Comment by coolman7** [comment]
`interface Window { plugins: any; }`
did not work for me. Anyway this is typescript related problem. I am happy with `window['plugins']` and this plugin works for me.
You may close the case.
Thank you again for your help

**Comment by tomloprod** [comment]
Glad yo have helped :-)
