### ISSUE TITLE
Unable to install plugin

### ISSUE THREAD

**Issue by anildfe** [tomloprod/cordova-plugin-appminimize#3]
Error: Failed to fetch plugin https://github.com/tomloprod/cordova-plugin-appminimize.git via registry.
Probably this is either a connection problem, or plugin spec is incorrect.
Check your connection and plugin name/version/URL.
Error: cmd: Command failed with exit code 4294963228 Error output:
npm ERR! addLocal Could not install C:\Users\ADUSAR~1\AppData\Local\Temp\npm-29516-a704077a\git-cache-d37c5de6\3c18afce1cebdd6e5f2ba2285aa798d5ef0b6283
npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/tomloprod/cordova-plugin-appminimize.git" "--save"
npm ERR! node v7.2.1
npm ERR! npm  v3.10.10
npm ERR! code EISDIR
npm ERR! errno -4068
npm ERR! syscall read

npm ERR! eisdir EISDIR: illegal operation on a directory, read
npm ERR! eisdir This is most likely not a problem with npm itself
npm ERR! eisdir and is related to npm not being able to find a package.json in
npm ERR! eisdir a package you are trying to install.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Projects\Amtrak\ionicApp\node_modules\npm-debug.log

**Comment by tomloprod** [comment]
Try with:

    cordova plugin add cordova-plugin-appminimize
