### ISSUE TITLE
Plugin not working

### ISSUE THREAD

**Issue by TeodorKolev** [tomloprod/cordova-plugin-appminimize#7]
Ionic 4.4.0. I have install plugin and add this code
```
this.platform.registerBackButtonAction(() => {
    console.log('test');
    this.appMinimize.minimize();
});
```
App did not minimize, neither console output is fired.

**Comment by tomloprod** [comment]
Try without `registerBackButtonAction()`. The plugin should work.

**Comment by zinzinday** [comment]
method registerBackButtonAction working but AppMinimize not work

**Comment by Thomas0921** [comment]
But I think mostly this plugin is used to make back button has home button behavior. Need this to work too

(Object() is not a function)

**Comment by Thomas0921** [comment]
**Update**: I got it working after trying the post written by you at [Ionic Forum](https://forum.ionicframework.com/t/how-put-app-in-background-minimize/33388/4?u=thomaskim47)

No working method (Stated in Ionic Native [Documentation](https://ionicframework.com/docs/native/app-minimize))
`this.appMinimize.minimize();`

Working method
`(<any>window).plugins.appMinimize.minimize();`
